Repository input-output-hk/ouroboros-high-assurance, pull requests merged in 2023-10, with the labels that each got.

#82 Enable communication of programs with their environments
  src/Ouroboros-Mini_Protocols-Chain_Sync.thy
  src/Ouroboros-Mini_Protocols-Ping_Pong.thy
  src/Ouroboros-Mini_Protocols-Request_Response.thy
  src/Ouroboros-Mini_Protocols.thy
Labels: type: enhancement

#85 Fix the typing of the `_Await` syntax constant
  src/Ouroboros-Mini_Protocols.thy
Labels: type: bugfix

#86 Improve pretty-printing of programs
  src/Ouroboros-Mini_Protocols.thy
Labels: type: improvement

#89 Add bound check in the definition of `index`
  src/Ouroboros-Mini_Protocols-Chain_Sync.thy
Labels: type: bugfix

#90 Turn `typed_import` and `typed_export` into abbreviations
  src/Ouroboros-Mini_Protocols.thy
Labels: type: bugfix

#92 Make `state_machine_bisimulation` use `Let_def` more often
  src/Ouroboros-Mini_Protocols.thy
Labels: type: enhancement
