Repository input-output-hk/ouroboros-high-assurance, pull requests merged in 2023-09, with the labels that each got.

#67 Switch to arbitrary party types with absolute denotations
  src/Ouroboros-Mini_Protocols-Ping_Pong.thy
  src/Ouroboros-Mini_Protocols-Request_Response.thy
  src/Ouroboros-Mini_Protocols.thy
Labels: type: enhancement

#71 Make the `follow_up` documentation use tenses consistently
  src/Ouroboros-Mini_Protocols.thy
Labels: type: bugfix

#70 Name the 2nd assumption of `up_to_embedding_is_sound`
  src/Ouroboros-Mini_Protocols.thy
Labels: type: improvement

#74 Implement a fragment of the chain synchronization protocol
  src/Ouroboros-Mini_Protocols-Chain_Sync.thy
  src/ROOT
Labels: type: enhancement

#79 Adapt heading to single-state-machine specification
  src/Ouroboros-Mini_Protocols-Ping_Pong.thy
  src/Ouroboros-Mini_Protocols-Request_Response.thy
Labels: type: bugfix

#80 Remove parenthesis around case patterns
  src/Ouroboros-Mini_Protocols-Request_Response.thy
Labels: type: improvement
